// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2ce2c86f-5af8-48d2-a6e0-8d769fb4bb53",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_nTGYRFTSV",
    "aws_user_pools_web_client_id": "1cvnaj5g87fdu1849d2p2vjcos"
}


export default awsmobile
